[project]
name = "fastapi-deferred-init"
description = "Faster FastAPI start-up time for Projects with many nested routers"
keywords = ["fastapi", "speed", "router"]
authors = [{ name = "Jan Vollmer", email = "jan@vllmr.dev" }]
dependencies = ["fastapi>=0.110.0"]
requires-python = ">=3.9"
readme = "README.md"
license = { text = "MIT" }
classifiers = ["Framework :: FastAPI"]
dynamic = ["version"]

[project.urls]
Source = "https://github.com/jvllmr/fastapi-deferred-init"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool]
[tool.pdm]
ignore_package_warnings = ["pre-commit"]
plugins = ["sync-pre-commit-lock"]

[tool.pdm.scripts]
test = "pytest"
post_install = {composite = ["pre-commit install", "pdm install --plugins"]}


[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.4.2",
    "black>=23.10.0",
    "ruff>=0.1.0",
    "pre-commit>=3.5.0",
    "mypy>=1.6.1",
    "tuna>=0.5.11",
    "httpx>=0.25.0",
]

[tool.isort]
profile = "black"

[tool.pdm.version]
source = "scm"
