[project]
name = "fastapi-deferred-init"
description = "Faster FastAPI start-up time for Projects with many nested routers"
keywords = ["fastapi", "speed", "router"]
authors = [{ name = "Jan Vollmer", email = "jan@vllmr.dev" }]
dependencies = ["fastapi>=0.112.3"]
requires-python = ">=3.9"
readme = "README.md"
license = { text = "MIT" }
classifiers = ["Framework :: FastAPI"]
dynamic = ["version"]

[project.urls]
Source = "https://github.com/jvllmr/fastapi-deferred-init"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool]
[tool.pdm]
ignore_package_warnings = ["pre-commit"]
# plugins = ["sync-pre-commit-lock"]

[tool.pdm.scripts]
test = "pytest"
full_test = {shell= "pytest", env= {FULL_TEST = "true"}}
benchmark = {shell= "pytest --benchmark-json benchmark.json", env= {FULL_TEST = "true"}}
post_install = {composite = ["pre-commit install", "pdm install --plugins --frozen-lock"]}


[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.4.4",
    "black>=23.12.1",
    "ruff>=0.6.3",
    "pre-commit>=3.8.0",
    "mypy>=1.11.2",
    "tuna>=0.5.11",
    "httpx>=0.27.2",
    "pytest-benchmark>=4.0.0",
]

[tool.isort]
profile = "black"

[tool.pdm.version]
source = "scm"

[tool.pycln]
all = true
